{
  "openapi": "3.1.0",
  "info": {
    "title": "Min-wallet",
    "description": "An app that enables you to manage your financial life",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3333",
      "description": "Development server"
    }
  ],
  "components": {
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "parameters": {
      "refreshTokenCookie": {
        "name": "refreshToken",
        "in": "cookie",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "The refresh token used for obtaining a new access token"
      }
    }
  },
  "paths": {
    "/register": {
      "post": {
        "description": "Route to create a new account",
        "summary": "Create a new account",
        "tags": ["User"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "John Doe",
                  "email": "johndoe@example.com",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "409": {
            "description": "E-mail already exists!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "E-mail already exists!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/sessions": {
      "post": {
        "description": "Route to log in the user",
        "summary": "Log in the user",
        "tags": ["User"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "email": "johndoe@example.com",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
                  }
                }
              }
            },
            "headers": {
              "Set-Cookie": {
                "schema": {
                  "type": "string",
                  "example": "refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9; Path=/; Secure; HttpOnly; SameSite=Strict; Domain=localhost"
                }
              }
            }
          },
          "400": {
            "description": "Invalid credentials!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Invalid credentials!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/me": {
      "get": {
        "description": "Route to user profile",
        "summary": "Get user profile",
        "tags": ["User"],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "c4433c6e-92fb-4cec-a639-cf28b7c34424",
                    "name": "John Doe",
                    "email": "johndoe@example.com",
                    "created_at": "2024-05-26T21:26:37.708Z",
                    "updated_at": "2024-05-26T21:26:37.708Z"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Unauthorized!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/profile": {
      "patch": {
        "description": "Route to update user profile",
        "summary": "Update user profile",
        "tags": ["User"],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "John Doe",
                  "email": "johndoe@example.com",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "c4433c6e-92fb-4cec-a639-cf28b7c34424",
                    "name": "John Doe",
                    "email": "johndoe@example.com",
                    "created_at": "2024-05-26T21:26:37.708Z",
                    "updated_at": "2024-05-26T21:26:37.708Z"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Unauthorized!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/token/refresh": {
      "patch": {
        "description": "Route to refresh user access token",
        "summary": "Refresh user access token",
        "tags": ["User"],
        "parameters": [
          {
            "$ref": "#/components/parameters/refreshTokenCookie"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "token": "c4433c6e-92fb-4cec-a639-cf28b7c34424"
                  }
                }
              }
            },
            "headers": {
              "Set-Cookie": {
                "description": "Refresh Token",
                "schema": {
                  "type": "string",
                  "example": "refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9; Path=/; Secure; HttpOnly; SameSite=Strict; Domain=localhost"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "headers": {
              "Set-Cookie": {
                "description": "Refresh Token",
                "schema": {
                  "type": "string",
                  "example": "refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9; Path=/; Secure; HttpOnly; SameSite=Strict; Domain=localhost"
                }
              }
            }
          }
        }
      }
    },
    "/forgot-password": {
      "post": {
        "description": "Route to request a password reset",
        "summary": "Request a password reset",
        "tags": ["User"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  }
                },
                "example": {
                  "email": "johndoe@example.com"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
                    "email": "johndoe@example.com"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource not found!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Resource not found!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/reset-password": {
      "put": {
        "description": "Route to update the password",
        "summary": "Update the password",
        "tags": ["User"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "token": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
                  "email": "johndoe@example.com",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Invalid or expired password reset token!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Invalid or expired password reset token!"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource not found!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Resource not found!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/transactions": {
      "post": {
        "description": "Route to create a new transaction",
        "summary": "Create a new transaction",
        "tags": ["Transaction"],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "value": {
                    "type": "number"
                  },
                  "date": {
                    "type": {
                      "type": "string"
                    }
                  },
                  "type": {
                    "type": "string"
                  }
                },
                "example": {
                  "title": "NodeJS course",
                  "description": "",
                  "value": -24.9,
                  "date": "2024-07-30T03:00:00.000Z",
                  "type": "EXPENSE"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "title": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "value": {
                      "type": "number"
                    },
                    "date": {
                      "type": {
                        "type": "string"
                      }
                    },
                    "type": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    },
                    "user_id": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "7b5d07be-e50c-4136-8b93-91143435561c",
                    "title": "NodeJS course",
                    "description": "",
                    "value": -24.9,
                    "date": "2024-05-31T12:46:35.468Z",
                    "type": "EXPENSE",
                    "created_at": "2024-05-31T12:46:35.468Z",
                    "updated_at": "2024-05-31T12:46:35.468Z",
                    "user_id": "c4433c6e-92fb-4cec-a639-cf28b7c34424"
                  }
                }
              }
            }
          },
          "400": {
            "description": "ValidationError",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "field": {
                            "type": "string"
                          },
                          "message": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "error": [
                      {
                        "field": "title",
                        "message": "Required"
                      },
                      {
                        "field": "value",
                        "message": "Expected number, received nan"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Unauthorized!"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "description": "Route to get transactions",
        "summary": "Get transactions",
        "tags": ["Transaction"],
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "name": "title",
            "in": "query",
            "description": "Filter transactions by title",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "Page number for pagination",
            "required": false,
            "schema": {
              "type": "integer",
              "example": 1
            }
          },
          {
            "name": "from",
            "in": "query",
            "description": "Start date for filtering transactions (YYYY-MM-DD)",
            "required": false,
            "schema": {
              "type": "string",
              "format": "date",
              "example": "2024-01-01"
            }
          },
          {
            "name": "to",
            "in": "query",
            "description": "End date for filtering transactions (YYYY-MM-DD)",
            "required": false,
            "schema": {
              "type": "string",
              "format": "date",
              "example": "2024-12-31"
            }
          },
          {
            "name": "order",
            "in": "query",
            "description": "Order of transactions (asc or desc)",
            "required": false,
            "schema": {
              "type": "string",
              "enum": ["asc", "desc"],
              "example": "asc"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "count": {
                      "type": "integer"
                    },
                    "pages": {
                      "type": "integer"
                    },
                    "next_page": {
                      "type": "string",
                      "nullable": true
                    },
                    "previous_page": {
                      "type": "string",
                      "nullable": true
                    },
                    "transactions": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "title": {
                            "type": "string"
                          },
                          "description": {
                            "type": "string"
                          },
                          "value": {
                            "type": "number"
                          },
                          "date": {
                            "type": "string",
                            "format": "date-time"
                          },
                          "type": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string",
                            "format": "date-time"
                          },
                          "updated_at": {
                            "type": "string",
                            "format": "date-time"
                          },
                          "user_id": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "count": 2,
                    "pages": 1,
                    "next_page": null,
                    "previous_page": null,
                    "transactions": [
                      {
                        "id": "e8ead8f4-24ca-45ea-b9ca-9828662cd612",
                        "title": "HBO Max",
                        "description": "",
                        "value": 40,
                        "date": "2024-08-01T03:00:00.000Z",
                        "type": "EXPENSE",
                        "created_at": "2024-08-01T19:13:51.444Z",
                        "updated_at": "2024-08-02T19:29:48.926Z",
                        "user_id": "319b76e5-be99-418b-b44b-c4eef395323a"
                      },
                      {
                        "id": "86e89e80-cfad-4d75-8d7e-22ced37c593b",
                        "title": "Teste",
                        "description": "",
                        "value": 20,
                        "date": "2024-07-30T03:00:00.000Z",
                        "type": "INCOME",
                        "created_at": "2024-08-02T18:51:50.650Z",
                        "updated_at": "2024-08-02T18:59:00.776Z",
                        "user_id": "319b76e5-be99-418b-b44b-c4eef395323a"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "ValidationError",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "field": {
                            "type": "string"
                          },
                          "message": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "error": [
                      {
                        "field": "title",
                        "message": "Required"
                      },
                      {
                        "field": "value",
                        "message": "Expected number, received nan"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Unauthorized!"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/transactions/{transactionId}": {
      "put": {
        "description": "Route to update a transaction",
        "summary": "Update a transaction",
        "tags": ["Transaction"],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "title": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "value": {
                      "type": "number"
                    },
                    "date": {
                      "type": {
                        "type": "string"
                      }
                    },
                    "type": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    },
                    "user_id": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "7b5d07be-e50c-4136-8b93-91143435561c",
                    "title": "NodeJS course",
                    "description": "",
                    "value": -24.9,
                    "date": "2024-05-31T12:46:35.468Z",
                    "type": "EXPENSE",
                    "created_at": "2024-05-31T12:46:35.468Z",
                    "updated_at": "2024-05-31T12:46:35.468Z",
                    "user_id": "c4433c6e-92fb-4cec-a639-cf28b7c34424"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Unauthorized!"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Resource not found!"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "Route to delete a transaction",
        "summary": "Delete a transaction",
        "tags": ["Transaction"],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Unauthorized!"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "error": "Resource not found!"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
